import { FiMail, FiSettings, FiUser } from "react-icons/fi";
import { AccountShell } from "@/components/account/AccountShell";
import { Badge } from "@/components/ui/Badge";
import { getCustomerAccountData } from "@/lib/account/data";

export default async function CustomerProfilePage() {
  const { profile } = await getCustomerAccountData();
  const initials = (profile.name || profile.email).split(/\s|@/).filter(Boolean).slice(0, 2).map((part) => part[0]?.toUpperCase()).join("");
  return <AccountShell profile={profile}><p className="eyebrow">Conta</p><h1 className="display-title mt-4 text-3xl font-semibold sm:text-4xl">Perfil</h1><p className="mt-3 text-sm leading-6 text-zinc-400">Dados associados às compras e ao acesso aos produtos.</p><section className="card mt-8 p-6 sm:p-8" aria-labelledby="profile-data-title"><div className="flex flex-col gap-5 sm:flex-row sm:items-center"><span className="grid h-20 w-20 place-items-center rounded-3xl border border-[#b8ff5c]/15 bg-[#b8ff5c]/10 text-xl font-black text-[#b8ff5c]">{initials}</span><div><Badge variant="success">Conta verificada por compra</Badge><h2 id="profile-data-title" className="mt-3 text-xl font-black">{profile.name || "Cliente EscalaHub"}</h2><p className="mt-1 text-sm text-zinc-500">{profile.email}</p></div></div><dl className="mt-8 grid gap-4 border-t border-white/[.07] pt-6 sm:grid-cols-2"><div className="rounded-2xl border border-white/[.07] bg-white/[.025] p-4"><dt className="flex items-center gap-2 text-xs font-bold text-zinc-500"><FiUser />Nome</dt><dd className="mt-2 text-sm font-semibold">{profile.name || "Não informado"}</dd></div><div className="rounded-2xl border border-white/[.07] bg-white/[.025] p-4"><dt className="flex items-center gap-2 text-xs font-bold text-zinc-500"><FiMail />E-mail</dt><dd className="mt-2 truncate text-sm font-semibold">{profile.email}</dd></div></dl><div className="mt-5 flex items-start gap-3 rounded-2xl border border-blue-400/15 bg-blue-400/[.06] p-4 text-sm leading-6 text-blue-100"><FiSettings className="mt-1 shrink-0" /><p>A estrutura já suporta foto e configurações de perfil. Alterações de cadastro serão habilitadas em uma etapa futura com validação de identidade.</p></div></section></AccountShell>;
}
